### ISSUE TITLE
Feedback for Casablanca 

### ISSUE THREAD

**Issue by aizadazh** [damilurg/casablanca#1]
In general everything is fine for me.
Молодец что оформил Readme.
Классно прям оформил DEMO.
По бургер меню такое же замечание, которое мне писал - при клике на любую область меню должно исчезать, но это мне кажется не принципиально.
Footer на мой взгляд немного высоковат, даже если в макете заданы определенные параметры, нужно высоту уменьшить.
В целом МОЛОДЕЦ!!!

**Comment by damilurg** [comment]
добавил код на закрытие меню по клику и нажатию на ESC.
Бургер поправил.
